offer block for detailed course page
zhashkevych/creatly-frontend pull request #39
Opened 2021-05-16 06:42 UTC by AlimovaKatrin

add output of offers

2021-05-17 06:50 UTC, NickBGor approved these changes

2021-05-17 09:30 UTC, eugenakin requested changes

2021-05-17 09:30 UTC, eugenakin commented on src/api/endpoints.js
> +    getOffersByCourse: (id) => `${API_URL}/courses/${id}/offers`,
это скорее getCourseOffers

2021-05-17 09:30 UTC, eugenakin commented on src/api/offers.js
> +export const apiGetOffersByCourse = (id) =>
и тут соответственно  apiGetCourseOffers

2021-05-17 09:30 UTC, eugenakin commented on src/components/Offer/Offer.js
> +                <OfferCard key={uuidv4()} offer={el} />
тут для key можно и индекс заюзать, что б не грузить еще вызовом функции на каждый оффер, они местами меняться при ре-рендерах не будут, так что и индекс сойдет

2021-05-17 09:30 UTC, eugenakin commented on src/components/Offer/Offer.js
> +          {offers.length > 1 ? (
по сути тут можно и не проверять если он один, а выводить с проверкой:
`<OfferCard key={index} offer={el} isVertical={offers.length === 1}>`

2021-05-17 09:30 UTC, eugenakin commented on src/components/Offer/OfferCard.js
> +  <OfferContainer vertical={!!isVertical}>
тут не нужно привидение к булю, т.к. у нас пропс описан уже как буль, значит должен быть буль всегда

2021-05-17 09:30 UTC, eugenakin commented on src/components/Offer/OfferCard.js
> +          <Benefit key={uuidv4()}>
тут тоже key - index сойдет

2021-05-17 09:30 UTC, eugenakin commented on src/components/Offer/OfferCard.js
> +} from 'COMPONENTS/Offer/styles/OfferStyle';
т.к. мы везде пишем приставку Styled, то давай уже этого придерживаться
то есть файл должен называться OfferStyled

2021-05-17 12:37 UTC, AlimovaKatrin commented on src/components/Offer/OfferCard.js
> +  <OfferContainer vertical={!!isVertical}>
Жень согласна ,что должен, изначально я просто прописывала `< OfferContainer vertical >`
Но верстка в таком случае начинает вести себя не ожиданно

2021-05-17 19:33 UTC, eugenakin commented on src/components/Offer/OfferCard.js
> +  <OfferContainer vertical={!!isVertical}>
я имею ввиду так:
`vertical={isVertical}`

2021-05-18 08:09 UTC, eugenakin approved these changes

2021-05-18 08:09 UTC, merged