catch block, module offers request
zhashkevych/creatly-frontend pull request #49
Opened 2021-05-24 11:23 UTC by AlimovaKatrin

2021-05-24 15:07 UTC, eugenakin requested changes

2021-05-24 15:07 UTC, eugenakin commented on src/components/PaidModule/PaidModule.js
> +import Offer from 'COMPONENTS/Offer';
поменяй default экспорт на именованный

2021-05-24 15:07 UTC, eugenakin commented on src/components/PaidModule/PaidModule.js
> +import Offer from 'COMPONENTS/Offer';
и удали src/components/PaidModule/styles/PaidModuleStyled.js, если он пустой)

2021-05-24 15:07 UTC, eugenakin commented on src/pages/CourseInfo/CourseInfo.js
> +import { PaidCourse } from '../../components/PaidCourse/PaidCourse';
и юзай алиасы - COMPONENTS/blah/blah/blah

2021-05-25 05:57 UTC, AlimovaKatrin commented on src/components/PaidCourse/PaidCourse.js
> +    apiGetCourseOffers(id).then(({ data }) => setOffers(() => data));
если честно, написала по привычке. Но вроде как если через кол бек передаешь, он незамедлительно обновит стейт

2021-05-25 11:17 UTC, eugenakin approved these changes

2021-05-25 11:17 UTC, merged