Katrin alimova/promocodes parcing
zhashkevych/creatly-frontend pull request #50
Opened 2021-05-25 15:02 UTC by AlimovaKatrin

- testing promocode for req - 'SUPER'
- changing of price

2021-05-25 21:57 UTC, eugenakin requested changes

2021-05-25 21:57 UTC, eugenakin commented on src/api/promocodes.js
> +export const apiGetPromocodes = (code) =>
apiGetPromocode, он один вроде

2021-05-25 21:57 UTC, eugenakin commented on src/api/promocodes.js
> +  makeRequest('GET')(endpoints.promocodes.getPromocode(code))().then(({ data }) => data);
.then тут не надо, вдруг нам потом надо будет что-то с респонса кроме данных

2021-05-25 21:57 UTC, eugenakin commented on src/components/Offer/Offer.js
> +  };
enter

2021-05-25 21:57 UTC, eugenakin commented on src/components/Offer/Offer.js
> +      const { offerIds, discountPercentage } = promocode;
enter

2021-05-25 21:57 UTC, eugenakin commented on src/components/Offer/Offer.js
> +          const { price } = el;
enter

2021-05-25 21:57 UTC, eugenakin commented on src/components/Offer/Offer.js
> +            {code && <Button onClick={getPromocode}>Применить</Button>}
давай сразу выведем кнопку, это проёб дизайна
но сделай тут наш инпут и что бы он был обязательным с ошибкой
посмотри на логине как

2021-05-25 21:57 UTC, eugenakin commented on src/components/Offer/Offer.js
> +  const onchangeHandler = ({ target: { value } }) => {
handleChange что б по красоте

2021-05-25 21:57 UTC, eugenakin commented on src/components/Offer/Offer.js
> +          offerIds.forEach((id) => {
тут offerIds.includes(id) как условие что б красиво

2021-05-25 21:57 UTC, eugenakin commented on src/utils/discount.js
> +export function getDiscountPrice(percent, originalPrice) {
думаю это нет смысла выносить в утилитки, пока не знаю где это еще может понадобиться кроме промокодов

2021-05-25 21:57 UTC, eugenakin commented on src/utils/discount.js
> +  const discountValue = originalPrice * (percent / 100);
тут четко все считает? без джс приколов? если процент дробный, то норм?

2021-05-25 21:57 UTC, eugenakin commented on src/components/PaidCourse/PaidCourse.js
> +  return <Offer offers={offers} setOffers={setOffers} />;
setOffers оберни в useCallback что б чилдрен лишний раз не ререндерился

2021-05-26 07:28 UTC, AlimovaKatrin commented on src/utils/discount.js
> +  const discountValue = originalPrice * (percent / 100);
Перепроверила - в бд принимает только целые числа, если скидос дробный то мы его округляем.  норм должно быть

2021-05-26 12:48 UTC, eugenakin requested changes

2021-05-26 12:48 UTC, eugenakin commented on src/components/Offer/Offer.js
> +          if (offerIds.includes(el.id)) {
я имел ввиду вместо foreach, разве так не сработает?

2021-05-26 14:46 UTC, AlimovaKatrin commented on src/components/Offer/Offer.js
> +          if (offerIds.includes(el.id)) {
includes `boolean` возвращает,  оффер айдис - это массив . И нам нужно найти схождения в двух списках (офферов и к айдишек к которым применяется скидка) я чет не знаю как по другому

2021-05-26 15:02 UTC, eugenakin commented on src/components/Offer/Offer.js
> +          if (offerIds.includes(el.id)) {
ну как я понял, ты перебираешь массив айдишников, и если там есть айдишник элемента - то записываеться скидка
это по сути тоже самое что сделать 
`if (offerIds.includes(el.id)) {
    price.discount = getDiscountPrice(discountPercentage, price.value);
}`
разве нет?)

2021-05-26 15:04 UTC, eugenakin commented
> @eugenakin Жень, я добавила еще уведомления если такого промокода не существует. Там есть повторяющаяся функция, может пришло время кастомного хука для уведомлений? :-)
> 
> И на днях будет новый дизайн для офферов и промокодов - кнопку в форме оставила как есть,выглядит не по дизайну ,но вроде прилично

если видишь что можно оптимищировать - то делай, но тут нужно подумать как
я уже сделал такой хук для уведомлпений в админке useAdminNitification, посмотри и скажи что думаешь)

2021-05-26 15:06 UTC, AlimovaKatrin commented on src/components/Offer/Offer.js
> +          if (offerIds.includes(el.id)) {
фаааак, вот я лох

2021-05-26 15:12 UTC, eugenakin approved these changes

2021-05-26 15:16 UTC, merged